import os
import subprocess32
import re
myinput = open('b.txt')
myoutput = open('b_out.txt', 'w')
p = subprocess32.Popen('./a.out', stdin=myinput, stdout=myoutput)
p.wait()
myoutput.flush()
myinput = open('c.txt')
myoutput = open('c_out.txt', 'w')
p = subprocess32.Popen('./a.out', stdin=myinput, stdout=myoutput)
p.wait()
myoutput.flush()
myinput = open('d.txt')
myoutput = open('d_out.txt', 'w')
p = subprocess32.Popen('./a.out', stdin=myinput, stdout=myoutput)
p.wait()
myoutput.flush()
myinput = open('e.txt')
myoutput = open('e_out.txt', 'w')
p = subprocess32.Popen('./a.out', stdin=myinput, stdout=myoutput)
p.wait()
myoutput.flush()
myinput = open('d.txt')
myoutput = open('d_out.txt', 'w')
p = subprocess32.Popen('./a.out', stdin=myinput, stdout=myoutput)
p.wait()
myoutput.flush()